version: "2.3"

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.1
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - /mnt/c/Users/mattchang/Desktop/csv-demo/:/usr/share/logstash/csv-demo
    ports:
      - "5044:5044"
    restart: always
